#!/bin/bash
# =============================================================================
# convert_to_gguf.sh
# Converts a HuggingFace model (safetensors) to GGUF using llama.cpp,
# then re-registers it with Ollama.
#
# Fixes: "Error: unknown data type: I32" from Ollama's built-in converter.
#
# NPU note: llama.cpp is built with -DGGML_CANN=ON so the resulting GGUF
# can be served by an Ollama binary that has CANN support (see build_ollama_npu.sh).
# Source the CANN toolkit environment (setenv.bash) before running this script.
# =============================================================================

set -e

MODEL_PATH="/villa/rhh25/mixtral"
MODEL_NAME="mixtral-local"
GGUF_OUT="${MODEL_PATH}/model-f16.gguf"     # where to write the GGUF
QUANT_OUT="${MODEL_PATH}/model-q4_k_m.gguf" # quantized version (smaller/faster)
MODELFILE_PATH="./Modelfile"
LLAMA_CPP_DIR="./llama.cpp"

echo "=== GGUF Conversion via llama.cpp ==="
echo "Source  : $MODEL_PATH"
echo "Output  : $GGUF_OUT"
echo "Quant   : $QUANT_OUT"

# ---------- 1. Install Python deps ----------
echo ""
echo "[1/5] Installing Python dependencies..."
pip install --break-system-packages --quiet \
    torch numpy sentencepiece transformers gguf protobuf

# ---------- 2. Clone llama.cpp if not present ----------
echo ""
echo "[2/5] Setting up llama.cpp..."
if [ ! -d "$LLAMA_CPP_DIR" ]; then
    git clone --depth=1 https://github.com/ggerganov/llama.cpp "$LLAMA_CPP_DIR"
    echo "[OK] Cloned llama.cpp"
else
    echo "[OK] llama.cpp already present, pulling latest..."
    git -C "$LLAMA_CPP_DIR" pull --quiet
fi

# Install llama.cpp Python requirements
pip install --break-system-packages --quiet -r "$LLAMA_CPP_DIR/requirements.txt" 2>/dev/null || true

# ---------- 3. Convert HF → GGUF (f16) ----------
echo ""
echo "[3/5] Converting HuggingFace model → GGUF (f16)..."
echo "      This may take 5-15 minutes depending on model size."

CONVERT_SCRIPT=""
# Try new name first, fall back to old name
if [ -f "$LLAMA_CPP_DIR/convert_hf_to_gguf.py" ]; then
    CONVERT_SCRIPT="$LLAMA_CPP_DIR/convert_hf_to_gguf.py"
elif [ -f "$LLAMA_CPP_DIR/convert.py" ]; then
    CONVERT_SCRIPT="$LLAMA_CPP_DIR/convert.py"
else
    echo "[ERROR] Could not find conversion script in llama.cpp directory."
    exit 1
fi

echo "Using: $CONVERT_SCRIPT"

python3 "$CONVERT_SCRIPT" \
    "$MODEL_PATH" \
    --outtype f16 \
    --outfile "$GGUF_OUT"

echo "[OK] GGUF written to: $GGUF_OUT"
ls -lh "$GGUF_OUT"

# ---------- 4. Quantize to Q4_K_M (optional but recommended) ----------
# Q4_K_M = ~4-bit quantisation, excellent quality/speed trade-off on 910B3.
# The 910B3 has 64 GB HBM per card; Q4_K_M lets you fit larger models per card.
echo ""
echo "[4/5] Quantizing to Q4_K_M (faster inference, ~50% smaller)..."

# Build llama-quantize if not already built.
# -DGGML_CANN=ON enables the Huawei Ascend CANN backend.
if [ ! -f "$LLAMA_CPP_DIR/llama-quantize" ] && [ ! -f "$LLAMA_CPP_DIR/quantize" ]; then
    echo "      Building llama.cpp quantize tool with CANN backend..."
    cmake -S "$LLAMA_CPP_DIR" -B "$LLAMA_CPP_DIR/build" \
        -DGGML_CANN=ON \
        -DCMAKE_BUILD_TYPE=Release \
        > /dev/null 2>&1
    cmake --build "$LLAMA_CPP_DIR/build" --config Release -j"$(nproc)" --target llama-quantize > /dev/null 2>&1
    cp "$LLAMA_CPP_DIR/build/bin/llama-quantize" "$LLAMA_CPP_DIR/" 2>/dev/null || \
    cp "$LLAMA_CPP_DIR/build/llama-quantize"     "$LLAMA_CPP_DIR/" 2>/dev/null || true
fi

QUANTIZE_BIN=""
for bin in "$LLAMA_CPP_DIR/llama-quantize" "$LLAMA_CPP_DIR/quantize" "$LLAMA_CPP_DIR/build/bin/llama-quantize"; do
    if [ -f "$bin" ]; then
        QUANTIZE_BIN="$bin"
        break
    fi
done

if [ -n "$QUANTIZE_BIN" ]; then
    "$QUANTIZE_BIN" "$GGUF_OUT" "$QUANT_OUT" Q4_K_M
    echo "[OK] Quantized model: $QUANT_OUT"
    ls -lh "$QUANT_OUT"
    USE_GGUF="$QUANT_OUT"
else
    echo "[WARN] quantize binary not found; skipping quantization. Using f16 GGUF."
    USE_GGUF="$GGUF_OUT"
fi

# ---------- 5. Re-create Modelfile + register with Ollama ----------
echo ""
echo "[5/5] Registering GGUF model with Ollama..."

cat > "$MODELFILE_PATH" <<EOF
# Generated by convert_to_gguf.sh — uses pre-converted GGUF file.
FROM $USE_GGUF

PARAMETER num_ctx        4096
PARAMETER num_predict    -1
PARAMETER temperature    0.7
PARAMETER top_p          0.9
PARAMETER repeat_penalty 1.1
PARAMETER num_gpu        -1

SYSTEM """You are a helpful AI assistant."""
EOF

echo "[OK] Modelfile:"
cat "$MODELFILE_PATH"

echo ""
echo "Creating Ollama model '$MODEL_NAME'..."
ollama create "$MODEL_NAME" -f "$MODELFILE_PATH"

echo ""
echo "=== Conversion & registration complete! ==="
echo "GGUF file : $USE_GGUF"
echo "Model name: $MODEL_NAME"
echo ""
echo "Verify with:  ollama list"
echo "Then launch:  bash start_server.sh"
